language: go

go:
  - master

git:
  depth: 1

branches:
  only:
  - master

before_install:
  - go get -t -v ./...

script:
#  - go test -v ./... -coverprofile=coverage.out -covermode=atomic
  - go test -v ./... -coverprofile=coverage.out -covermode=count

after_success:
#  - bash <(curl -s https://codecov.io/bash) -t ede87629-f9e8-4bc4-b308-dec35cf09e95
   - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken VP09HdcbrdgqakGuisDUYeMGc16dlXOqH

