# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: hiboot
  profiles:
    include:
    - foo
  dataSourceType: bolt

logging:
  level: debug

dataSource:
  database: hi.db
  mode: 0600
  timeout: 1
