# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: hiboot
  profiles:
    include:
    - foo

logging:
  level: info

dataSources:
- type: bolt
  database: hi.db
  mode: 0600
  timeout: 1
