
pipeline:
  name: javawar
  identifiers:
  - pom.xml
  targets:
  - target/${app}.war
  - target/${app}-${version}.war
  fromdir: target/deployments
  deploymentfile: ROOT.war
  imagestream: s2i-java-war:latest
  versionfrom: pom.xml
  options: -Xms128m -Xmx512m -Xss512k
  buildcommand: mvn clean install -U


