
pipeline:
  name: java-war
  identifiers:
  - pom.xml
  deploymentfile: ROOT.war
  imagestream: s2i-java-war:latest
  env:
  - name: APP_OPTIONS
    value: -Xms128m -Xmx512m -Xss512k -XX:+ExitOnOutOfMemoryError
  - name: SPRING_PROFILES_ACTIVE
    value: ${profile}
  - name: TZ
    value: Asia/Shanghai
  script: |
    mvn clean package -U -Dmaven.test.skip=true -Djava.net.preferIPv4Stack=true
    if [[ $? == 0 ]]; then
      echo "Successful."
    else
      echo "Failed!"
    fi


