
pipeline:
  name: java
  identifiers:
  - pom.xml
  configfiles:
  - src/main/resources/application.yml
  - src/main/resources/application-${profile}.yml
  targets:
  - target/${app}.jar
  - target/${app}-${version}.jar
  fromdir: target/deployments
  deploymentfile: app.jar
  imagestream: s2i-java:latest
  versionfrom: pom.xml
  options: -Xms128m -Xmx512m -Xss512k
  buildcommand: mvn clean install -U


