# to be overwritten at runtime

pipeline:
  profile: ${profile}
  image_tag: latest
  scm_ref: master
  scm_url: http://github.com
  repository_url: http://maven.aliyun.com/nexus/content/groups/public
  docker_registry: docker-registry.default.svc:5000
  replicas: 1
  ports:
  - name: 8080-tcp
    port: 8080
    container_port: 8080
    protocol: TCP