apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ${app.name}
    version: ${app.version}
  name: ${app.name}-${app.version}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app.name}
      version: ${app.version}
  template:
    metadata:
      labels:
        app: ${app.name}
        version: ${app.version}
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: ${app.options} -Djava.net.preferIPv4Stack=true -Dfile.encoding=utf-8 -Djava.security.egd=file:///dev/./urandom
        image: example/${app.name}:${app.version}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        name: ${app.name}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 7575
          name: grpc
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
