# config file for testing

server:
  port: 8081

logging:
  level: debug

grpc:
  client:
    hello-world-service:
      host: localhost # or greeter-server.${app.project}-${app.profiles.active}
      port: 7575

